<a href="https://colab.research.google.com/github/RoRdil31/Hongcheon-gun-Project/blob/main/%ED%99%8D%EC%B2%9C%EA%B5%B0_%EA%B3%B5%EB%AA%A8%EC%A0%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Library setting.

In [8]:
#!pip install koreanize-matplotlib
import koreanize_matplotlib
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

color = sns.color_palette('pastel')
plt.rc('font',family="Malgun Gothic")
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

!apt-get update -qq
!apt-get install fonts-nanum -qq

font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
font_prop = fm.FontProperties(fname=font_path)
plt.rcParams['font.family'] = font_prop.get_name()

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package fonts-nanum.
(Reading database ... 123599 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20200506-1_all.deb ...
Unpacking fonts-nanum (20200506-1) ...
Setting up fonts-nanum (20200506-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...

In [7]:
import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=UserWarning, module="matplotlib.font_manage")

In [23]:
%pwd

'/root'

In [24]:
%ls

'구조 종별 신고 재난 데이터 2020-2022(홍천).cell'   local_file.xlsx

In [25]:
%cd /content

/content

In [26]:
%pwd

'/content'

# Data Upload and Preprocessing

In [29]:
# url = 'https://github.com/RoRdil31/Hongcheon-gun-Project.git/구조종별신고재난데이터20202022홍천.xlsx'

# import requests

# response = requests.get(url)
# with open('local_file.xlsx','wb') as f:
#   f.write(response.content)

df = pd.read_excel('구조종별신고재난데이터20202022홍천.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4394 entries, 0 to 4393
Data columns (total 58 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   재난구조보고서번호  4394 non-null   object
 1   사고원인       4238 non-null   object
 2   처리결과구분명    4394 non-null   object
 3   신고일자       4394 non-null   int64
 4   신고시각       4394 non-null   int64
 5   신고연도       4394 non-null   int64
 6   계절구분명      2998 non-null   object
 7   분기구분       2998 non-null   float64
 8   신고월        4394 non-null   int64
 9   신고일        4394 non-null   int64
 10  신고시        4394 non-null   int64
 11  신고분        4394 non-null   int64
 12  출동일자       4394 non-null   int64
 13  출동시각       4394 non-null   int64
 14  출동연도       4394 non-null   int64
 15  출동월        4394 non-null   int64
 16  출동일        4394 non-null   int64
 17  출동시        4394 non-null   int64
 18  출동분        4394 non-null   int64
 19  현장도착일자     4366 non-null   float64
 20  현장도착시각     4394 non-null   object
 21  현장도착연도     4366 non-null   float64
 22  현장도착월      4366 non-null   float64
 23  현장도착일      4366 non-null   float64
 24  현장도착시      4366 non-null   float64
 25  현장도착분      4366 non-null   float64
 26  구조완료일자     4049 non-null   float64
 27  구조완료시각     4394 non-null   object
 28  구조완료연도     4049 non-null   float64
 29  구조완료월      4049 non-null   float64
 30  구조완료일      4049 non-null   float64
 31  구조완료시      4049 non-null   float64
 32  구조완료분      4049 non-null   float64
 33  귀소일자       4394 non-null   int64
 34  귀소시각       4394 non-null   int64
 35  귀소연도       4394 non-null   int64
 36  귀소월        4394 non-null   int64
 37  귀소일        4394 non-null   int64
 38  귀소시        4394 non-null   int64
 39  귀소분        4394 non-null   int64
 40  시도명        4394 non-null   object
 41  시군구명       4394 non-null   object
 42  읍면동명       4394 non-null   object
 43  읍면동구분명     4394 non-null   object
 44  위치정보X      3064 non-null   float64
 45  위치정보Y      3064 non-null   float64
 46  현장소방서거리    4394 non-null   float64
 47  사고장소명      4394 non-null   object
 48  사고장소세부명    4394 non-null   object
 49  시간단위기온     3250 non-null   float64
 50  시간단위강수량    1741 non-null   float64
 51  시간단위풍속     3250 non-null   float64
 52  시간단위풍향     3250 non-null   float64
 53  시간단위습도     3250 non-null   float64
 54  시간단위적설량    1464 non-null   float64
 55  소방서명       3250 non-null   object
 56  서센터명       2429 non-null   object
 57  소방지역대명     821 non-null    object
dtypes: float64(22), int64(21), object(15)
memory usage: 1.9+ MB

In [30]:
df.shape

(4394, 58)

## Object Data

In [32]:
df.describe(include='object')

,재난구조보고서번호,사고원인,처리결과구분명,계절구분명,현장도착시각,구조완료시각,시도명,시군구명,읍면동명,읍면동구분명,사고장소명,사고장소세부명,소방서명,서센터명,소방지역대명
count,4394,4238,4394,2998,4394,4394,4394,4394,4394,4394,4394,4394,3250,2429,821
unique,4393,146,19,4,1637,997,1,1,10,2,116,195,7,31,10
top,20214208202S00924,기타 사고,안전조치,여름,000nan,000nan,강원도,홍천군,홍천읍,면,단독주택,단독주택,홍천소방서,홍천119구조대,북방119지역대
freq,2,435,2109,1369,28,345,4394,4394,1176,3218,1126,941,3130,1030,192

### 중복 데이터 제거

In [46]:
df.loc[df['재난구조보고서번호']=='20214208202S00924']

,재난구조보고서번호,사고원인,처리결과구분명,신고일자,신고시각,신고연도,계절구분명,분기구분,신고월,신고일,...,사고장소세부명,시간단위기온,시간단위강수량,시간단위풍속,시간단위풍향,시간단위습도,시간단위적설량,소방서명,서센터명,소방지역대명
3238,20214208202S00924,고드름 제거,안전조치,20211228,111100,2021,NaN,NaN,12,28,...,단독주택,-8.0,10.0,0.0,0.0,78.0,10.0,홍천소방서,홍천119구조대,NaN
3239,20214208202S00924,고드름 제거,안전조치,20211228,111100,2021,NaN,NaN,12,28,...,단독주택,-8.0,10.0,0.0,0.0,78.0,10.0,홍천소방서,홍천119구조대,NaN

In [58]:
dupl_rows = df[df['재난구조보고서번호']=='20214208202S00924'].index
df = df.drop(dupl_rows[1:])
df.describe(include='object')

,재난구조보고서번호,사고원인,처리결과구분명,계절구분명,현장도착시각,구조완료시각,시도명,시군구명,읍면동명,읍면동구분명,사고장소명,사고장소세부명,소방서명,서센터명,소방지역대명
count,4393,4237,4393,2998,4393,4393,4393,4393,4393,4393,4393,4393,3249,2428,821
unique,4393,146,19,4,1637,997,1,1,10,2,116,195,7,31,10
top,20204208102S00001,기타 사고,안전조치,여름,000nan,000nan,강원도,홍천군,홍천읍,면,단독주택,단독주택,홍천소방서,홍천119구조대,북방119지역대
freq,1,435,2108,1369,28,345,4393,4393,1175,3218,1125,940,3129,1029,192

### Nan Data 제거 or 보류

In [59]:
df['현장도착시각'].value_counts()
# df[['현장도착시각','구조완료시각']].value_counts()

현장도착시각
000nan    28
125600    13
142000    12
131600    12
151400    11
          ..
234600     1
80700      1
1913       1
194100     1
215700     1
Name: count, Length: 1637, dtype: int64

## Number Data

In [60]:
df.describe()

,신고일자,신고시각,신고연도,분기구분,신고월,신고일,신고시,신고분,출동일자,출동시각,...,귀소분,위치정보X,위치정보Y,현장소방서거리,시간단위기온,시간단위강수량,시간단위풍속,시간단위풍향,시간단위습도,시간단위적설량
count,4.393000e+03,4393.000000,4393.000000,2998.000000,4393.000000,4393.000000,4393.000000,4393.000000,4.393000e+03,4393.000000,...,4393.000000,3063.000000,3063.000000,4393.000000,3249.000000,1740.000000,3249.000000,3249.000000,3249.000000,1463.000000
mean,2.020928e+07,137331.277032,2020.852493,2.636424,7.408832,15.570225,13.456180,28.901206,2.020928e+07,137689.392215,...,29.780332,37.687488,128.077480,10.263419,19.419821,8.629885,1.431210,161.175746,67.194829,9.915926
std,8.006015e+03,44558.796942,0.804192,0.951914,2.740929,8.914114,4.452333,17.465599,8.006014e+03,44506.065994,...,17.377171,0.215317,0.416907,15.718139,10.074925,5.276247,1.092529,110.519525,20.330684,0.842874
min,2.020010e+07,300.000000,2020.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.020010e+07,400.000000,...,0.000000,37.089806,126.925000,0.000000,-16.000000,0.000000,0.000000,0.000000,8.000000,1.000000
25%,2.020082e+07,104800.000000,2020.000000,2.000000,7.000000,8.000000,10.000000,14.000000,2.020082e+07,105100.000000,...,15.000000,37.615447,127.826063,3.000000,15.000000,10.000000,1.000000,70.000000,53.000000,10.000000
50%,2.021073e+07,135700.000000,2021.000000,3.000000,8.000000,16.000000,13.000000,28.000000,2.021073e+07,140000.000000,...,30.000000,37.693760,127.916518,7.000000,23.000000,10.000000,1.000000,160.000000,69.000000,10.000000
75%,2.022011e+07,170100.000000,2022.000000,3.000000,9.000000,23.000000,17.000000,44.000000,2.022011e+07,170400.000000,...,45.000000,37.779730,128.251452,13.000000,26.000000,10.000000,2.000000,270.000000,85.000000,10.000000
max,2.022123e+07,235900.000000,2022.000000,4.000000,12.000000,31.000000,23.000000,59.000000,2.022123e+07,235900.000000,...,59.000000,38.525044,129.301400,712.000000,36.000000,57.000000,10.000000,360.000000,100.000000,10.000000

In [62]:
df.isnull().sum()

재난구조보고서번호       0
사고원인          156
처리결과구분명         0
신고일자            0
신고시각            0
신고연도            0
계절구분명        1395
분기구분         1395
신고월             0
신고일             0
신고시             0
신고분             0
출동일자            0
출동시각            0
출동연도            0
출동월             0
출동일             0
출동시             0
출동분             0
현장도착일자         28
현장도착시각          0
현장도착연도         28
현장도착월          28
현장도착일          28
현장도착시          28
현장도착분          28
구조완료일자        345
구조완료시각          0
구조완료연도        345
구조완료월         345
구조완료일         345
구조완료시         345
구조완료분         345
귀소일자            0
귀소시각            0
귀소연도            0
귀소월             0
귀소일             0
귀소시             0
귀소분             0
시도명             0
시군구명            0
읍면동명            0
읍면동구분명          0
위치정보X        1330
위치정보Y        1330
현장소방서거리         0
사고장소명           0
사고장소세부명         0
시간단위기온       1144
시간단위강수량      2653
시간단위풍속       1144
시간단위풍향       1144
시간단위습도       1144
시간단위적설량      2930
소방서명         1144
서센터명         1965
소방지역대명       3572
dtype: int64